version: '3.5'

services:
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
    - network_db
  
  app:
    build:             
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: 'cyber-phishing'
    command: python manage.py runserver 0.0.0.0:3000
    depends_on:
      - db
    networks:
    - network_db
    ports:
      - 3000:3000
    env_file:
      - ./.env

networks:
  network_db:
    driver: bridge
